%YAML 1.1
# SPDX-License-Identifier: MIT
# Copyright © 2021 André Santos
---
name: haros_plugin_cbmc
version: 0.1.0
rules:
    counterexample:
        name: Counterexample Found
        description: "CBMC found a counterexample."
        tags:
            - software-model-checking
            - cbmc
            - hpl
            - computation-graph
